const GET_ALL = 'GET_ALL';
const PEOPLE_LIST = 'PEOPLE_LIST';
const PEOPLE_LIST_REQUEST = 'PEOPLE_LIST_REQUEST';
const PEOPLE_LIST_SUCCESS = 'PEOPLE_LIST_SUCCESS';
const PEOPLE_LIST_FAILURE = 'PEOPLE_LIST_FAILURE';
const ADD = 'ADD';
const ADD_PERSON_REQUEST = 'ADD_PERSON_REQUEST';
const ADD_PERSON_SUCCESS = 'ADD_PERSON_SUCCESS';
const ADD_PERSON_FAILURE = 'ADD_PERSON_FAILURE';
const DELETE_PERSON_REQUEST = 'DELETE_PERSON_REQUEST';
const DELETE_PERSON_SUCCESS = 'DELETE_PERSON_SUCCESS';
const DELETE_PERSON_FAILURE = 'DELETE_PERSON_FAILURE';
const DELETE = 'DELETE';
const UPDATE_PERSON_REQUEST = 'UPDATE_PERSON_REQUEST';
const UPDATE_PERSON_SUCCESS = 'UPDATE_PERSON_SUCCESS';
const UPDATE_PERSON_FAILURE = 'UPDATE_PERSON_FAILURE';
const UPDATE = 'UPDATE';

const types = {
  GET_ALL,
  PEOPLE_LIST,
  PEOPLE_LIST_REQUEST,
  PEOPLE_LIST_FAILURE,
  PEOPLE_LIST_SUCCESS,
  ADD_PERSON_REQUEST,
  ADD_PERSON_SUCCESS,
  ADD_PERSON_FAILURE,
  ADD,
  DELETE_PERSON_REQUEST,
  DELETE_PERSON_SUCCESS,
  DELETE_PERSON_FAILURE,
  DELETE,
  UPDATE_PERSON_REQUEST,
  UPDATE_PERSON_SUCCESS,
  UPDATE_PERSON_FAILURE,
  UPDATE,
};

export default types;
