const ACTORS_LIST_REQUEST = 'ACTORS_LIST_REQUEST';
const ACTORS_LIST_SUCCESS = 'ACTORS_LIST_SUCCESS';
const ACTORS_LIST_FAILURE = 'ACTORS_LIST_FAILURE';
const ADD_ACTOR_REQUEST = 'ADD_ACTOR_REQUEST';
const ADD_ACTOR_SUCCESS = 'ADD_ACTOR_SUCCESS';
const ADD_ACTOR_FAILURE = 'ADD_ACTOR_FAILURE';
const GET_ALL = 'GET_ALL';
const ADD = 'ADD';
const DELETE_ACTOR_REQUEST = 'DELETE_ACTOR_REQUEST';
const DELETE_ACTOR_SUCCESS = 'DELETE_ACTOR_SUCCESS';
const DELETE_ACTOR_FAILURE = 'DELETE_ACTOR_FAILURE';
const DELETE = 'DELETE';

const types = {
  ACTORS_LIST_REQUEST,
  ACTORS_LIST_SUCCESS,
  ACTORS_LIST_FAILURE,
  ADD_ACTOR_REQUEST,
  ADD_ACTOR_SUCCESS,
  ADD_ACTOR_FAILURE,
  GET_ALL,
  ADD,
  DELETE_ACTOR_REQUEST,
  DELETE_ACTOR_SUCCESS,
  DELETE_ACTOR_FAILURE,
  DELETE,
};

export default types;
