const MOVIE_LIST_REQUEST = 'MOVIE_LIST_REQUEST';
const MOVIE_LIST_SUCCESS = 'MOVIE_LIST_SUCCESS';
const MOVIE_LIST_FAILURE = 'MOVIE_LIST_FAILURE';
const ADD_MOVIE_REQUEST = 'ADD_MOVIE_REQUEST';
const ADD_MOVIE_SUCCESS = 'ADD_MOVIE_SUCCESS';
const ADD_MOVIE_FAILURE = 'ADD_MOVIE_FAILURE';
const GET_ALL = 'GET_ALL';
const ADD = 'ADD';
const UPDATE_MOVIE_REQUEST = 'UPDATE_MOVIE_REQUEST';
const UPDATE_MOVIE_SUCCESS = 'UPDATE_MOVIE_SUCCESS';
const UPDATE_MOVIE_FAILURE = 'UPDATE_MOVIE_FAILURE';
const UPDATE = 'UPDATE';
const DELETE_MOVIE_REQUEST = 'DELETE_MOVIE_REQUEST';
const DELETE_MOVIE_SUCCESS = 'DELETE_MOVIE_SUCCESS';
const DELETE_MOVIE_FAILURE = 'DELETE_MOVIE_FAILURE';
const PATCH_DIRECTOR_REQUEST = 'PATCH_DIRECTOR_REQUEST';
const PATCH_DIRECTOR_SUCCESS = 'PATCH_DIRECTOR_SUCCESS';
const PATCH_DIRECTOR_FAILURE = 'PATCH_DIRECTOR_FAILURE';
const DELETE = 'DELETE';

const types = {
  MOVIE_LIST_REQUEST,
  MOVIE_LIST_SUCCESS,
  MOVIE_LIST_FAILURE,
  GET_ALL,
  ADD,
  ADD_MOVIE_REQUEST,
  ADD_MOVIE_SUCCESS,
  ADD_MOVIE_FAILURE,
  UPDATE_MOVIE_REQUEST,
  UPDATE_MOVIE_SUCCESS,
  UPDATE_MOVIE_FAILURE,
  UPDATE,
  DELETE_MOVIE_REQUEST,
  DELETE_MOVIE_SUCCESS,
  DELETE_MOVIE_FAILURE,
  PATCH_DIRECTOR_REQUEST,
  PATCH_DIRECTOR_SUCCESS,
  PATCH_DIRECTOR_FAILURE,
  DELETE,
};

export default types;
